package roll

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// Opcode identifies a bytecode instruction executed by the roll VM.
type Opcode uint8

const (
	// OpRollDice evaluates a single dice term and pushes its result on the VM stack.
	OpRollDice Opcode = iota
	// OpRollGroup aggregates previously computed child results into a grouped result.
	OpRollGroup
	// OpPushNumber pushes a numeric literal onto the VM stack.
	OpPushNumber
	// OpBinary applies an arithmetic operator to the top two VM stack values.
	OpBinary
	// OpFunc applies a math function to the top VM stack value.
	OpFunc
)

func (op Opcode) String() string {
	switch op {
	case OpRollDice:
		return "roll_dice"
	case OpRollGroup:
		return "roll_group"
	case OpPushNumber:
		return "push_number"
	case OpBinary:
		return "binary"
	case OpFunc:
		return "func"
	default:
		return "unknown"
	}
}

// FuncType identifies a math function.
type FuncType int

const (
	// FuncFloor rounds toward negative infinity.
	FuncFloor FuncType = iota
	// FuncRound rounds toward zero below a half and toward positive infinity at or above it.
	FuncRound
	// FuncCeil rounds toward positive infinity.
	FuncCeil
	// FuncAbs returns the absolute value.
	FuncAbs
)

// String returns the notation for the math function.
func (f FuncType) String() string {
	switch f {
	case FuncFloor:
		return "floor"
	case FuncRound:
		return "round"
	case FuncCeil:
		return "ceil"
	case FuncAbs:
		return "abs"
	default:
		return "?"
	}
}

// BinaryOpType identifies an arithmetic operator.
type BinaryOpType int

const (
	// BinaryAdd adds two values.
	BinaryAdd BinaryOpType = iota
	// BinarySub subtracts two values.
	BinarySub
	// BinaryMul multiplies two values.
	BinaryMul
	// BinaryDiv divides two values.
	BinaryDiv
	// BinaryMod returns the modulus of two values.
	BinaryMod
	// BinaryPow raises a value to a power.
	BinaryPow
)

// String returns the notation for the binary operator.
func (op BinaryOpType) String() string {
	switch op {
	case BinaryAdd:
		return "+"
	case BinarySub:
		return "-"
	case BinaryMul:
		return "*"
	case BinaryDiv:
		return "/"
	case BinaryMod:
		return "%"
	case BinaryPow:
		return "**"
	default:
		return "?"
	}
}

// Instruction is a single bytecode operation.
type Instruction struct {
	Op  Opcode
	Arg int
}

// Program is a compiled roll program ready for VM execution.
type Program struct {
	Code       []Instruction
	DiceTerms  []DiceTerm
	GroupTerms []GroupTerm
	Rendered   string
	MaxDepth   int
}

// String returns the normalized notation generated by the compiler.
func (p *Program) String() string {
	if p == nil {
		return ""
	}
	return p.Rendered
}

// DiceTerm captures the semantics of a single dice instruction.
type DiceTerm struct {
	Multiplier int
	Die        Die
	// Sides, when set, is evaluated at roll time to determine the number of
	// faces; Die is nil in that case.
	Sides     *Program
	Modifier  int
	Exploding *ExplodingOp
	Limit     *LimitOp
	Success   *ComparisonOp
	Failure   *ComparisonOp
	Rerolls   []RerollOp
	Sort      SortType
	Match     *MatchOp
}

// GroupTerm captures the aggregation semantics of a grouped instruction.
type GroupTerm struct {
	Modifier   int
	Limit      *LimitOp
	Success    *ComparisonOp
	Failure    *ComparisonOp
	Combined   bool
	Negative   bool
	ChildCount int
}

// ComparisonType is the type of comparison.
type ComparisonType int

const (
	// Equals matches only values that are equal to the comparison value.
	Equals ComparisonType = iota
	// GreaterThan matches only values greater than the comparison value.
	GreaterThan
	// LessThan matches only values less than the comparison value.
	LessThan
)

// ComparisonOp is the operation that defines how you compare against a roll.
type ComparisonOp struct {
	Type      ComparisonType
	Value     int
	Inclusive bool
}

// Match returns true if the given value compares positively against the op val.
func (op *ComparisonOp) Match(val int) bool {
	switch op.Type {
	case Equals:
		return val == op.Value
	case GreaterThan:
		if op.Inclusive {
			return val >= op.Value
		}
		return val > op.Value
	case LessThan:
		if op.Inclusive {
			return val <= op.Value
		}
		return val < op.Value
	}
	return false
}

// String returns the string representation of the comparison operator.
func (op *ComparisonOp) String() string {
	switch op.Type {
	case Equals:
		return fmt.Sprintf("=%d", op.Value)
	case GreaterThan:
		if op.Inclusive {
			return fmt.Sprintf(">=%d", op.Value)
		}
		return fmt.Sprintf(">%d", op.Value)
	case LessThan:
		if op.Inclusive {
			return fmt.Sprintf("<=%d", op.Value)
		}
		return fmt.Sprintf("<%d", op.Value)
	}
	return ""
}

// ExplodingType is the type of exploding die.
type ExplodingType int

const (
	// Exploding adds new dice for each roll satisfying the exploding condition.
	Exploding ExplodingType = iota
	// Compounded adds to a single new result for each roll.
	Compounded
	// Penetrating is like Exploding, except each die result has a -1 modifier.
	Penetrating
)

// ExplodingOp is the operation that defines how a dice roll explodes.
type ExplodingOp struct {
	*ComparisonOp
	Type ExplodingType
}

// Match returns true if the given value compares positively against the exploding op.
func (e ExplodingOp) Match(val int, die Die) bool {
	if e.ComparisonOp != nil {
		return e.ComparisonOp.Match(val)
	}
	switch d := die.(type) {
	case NormalDie:
		return val == int(d)
	case PercentileDie:
		return val == 100
	}
	return false
}

// String returns the string representation of the exploding dice operation.
func (e ExplodingOp) String() (output string) {
	switch e.Type {
	case Exploding:
		output = "!"
	case Compounded:
		output = "!!"
	case Penetrating:
		output = "!p"
	}

	if e.ComparisonOp != nil {
		output += strings.TrimPrefix(e.ComparisonOp.String(), "=")
	}
	return output
}

// LimitType is the type of roll limitation.
type LimitType int

const (
	// KeepHighest indicated we should keep the highest results.
	KeepHighest LimitType = iota
	// KeepLowest indicated we should keep the lowest results.
	KeepLowest
	// DropHighest indicated we should drop the highest results.
	DropHighest
	// DropLowest indicated we should drop the lowest results.
	DropLowest
)

// LimitOp is the operation that defines how dice roll results are limited.
type LimitOp struct {
	Amount int
	Type   LimitType
}

func (op LimitOp) String() (output string) {
	switch op.Type {
	case KeepHighest:
		output = "kh"
	case KeepLowest:
		output = "kl"
	case DropHighest:
		output = "dh"
	case DropLowest:
		output = "dl"
	}

	if op.Amount > 1 {
		output += strconv.Itoa(op.Amount)
	}

	return
}

// MatchOp describes a dice matching modifier (mt counts matches, m is visual only).
type MatchOp struct {
	MinCount   int
	Visual     bool
	Comparison *ComparisonOp
}

// String returns the string representation of the dice matching modifier.
func (m MatchOp) String() (output string) {
	output = "mt"
	if m.Visual {
		output = "m"
	}
	if m.MinCount != 2 {
		output += strconv.Itoa(m.MinCount)
	}
	if m.Comparison != nil {
		output += m.Comparison.String()
	}
	return output
}

// RerollOp is the operation that defines how dice are rerolled.
type RerollOp struct {
	*ComparisonOp
	Once bool
}

// String returns the string representation of the reroll operation.
func (e RerollOp) String() (output string) {
	output = "r"
	if e.Once {
		output = "ro"
	}

	return output + strings.TrimPrefix(e.ComparisonOp.String(), "=")
}

// SortType is the type of sorting to use for dice roll results.
type SortType int

// String return the string representation of a SortType value.
func (t SortType) String() string {
	switch t {
	case Unsorted:
		return ""
	case Ascending:
		return "s"
	case Descending:
		return "sd"
	}

	return ""
}

const (
	// Unsorted doesn't sort dice rolls.
	Unsorted SortType = iota
	// Ascending sorts dice rolls from lowest to highest.
	Ascending
	// Descending sorts dice rolls from highest to lowest.
	Descending
)

// Limits configures compiler and evaluator safety limits.
type Limits struct {
	MaxDieSize     int
	MaxRollsPerDie int
	MaxRollsTotal  int
	MaxEvalDepth   int
}

// DefaultLimits are the package-level defaults used by Parse and ParseString.
var DefaultLimits = Limits{
	MaxDieSize:     1000000,
	MaxRollsPerDie: 1000000,
	MaxRollsTotal:  1000000,
	MaxEvalDepth:   256,
}

func (l Limits) normalized() Limits {
	if l.MaxDieSize <= 0 {
		l.MaxDieSize = DefaultLimits.MaxDieSize
	}
	if l.MaxRollsPerDie <= 0 {
		l.MaxRollsPerDie = DefaultLimits.MaxRollsPerDie
	}
	if l.MaxRollsTotal <= 0 {
		l.MaxRollsTotal = DefaultLimits.MaxRollsTotal
	}
	if l.MaxEvalDepth <= 0 {
		l.MaxEvalDepth = DefaultLimits.MaxEvalDepth
	}
	return l
}

// ErrUnsafeDie is raised when a die configuration is categorically unsafe.
type ErrUnsafeDie string

func (e ErrUnsafeDie) Error() string {
	return fmt.Sprintf("unsafe die type %q", string(e))
}

// ErrLimitExceeded is raised when compiler or evaluator safety limits are exceeded.
type ErrLimitExceeded string

func (e ErrLimitExceeded) Error() string { return string(e) }

// ErrDivisionByZero is raised when a division or modulus operation uses a zero divisor.
type ErrDivisionByZero string

func (e ErrDivisionByZero) Error() string { return string(e) }

// ErrInvalidDieSize is raised when a computed die size is not a whole number.
type ErrInvalidDieSize string

func (e ErrInvalidDieSize) Error() string { return string(e) }

// ErrNonConstantDieSize is raised when a die size expression depends on rolled dice.
type ErrNonConstantDieSize string

func (e ErrNonConstantDieSize) Error() string { return string(e) }

type rollContext struct {
	limits     Limits
	totalRolls int
}

func (ctx *rollContext) recordRoll(perDie *int) error {
	(*perDie)++
	if *perDie > ctx.limits.MaxRollsPerDie {
		return ErrLimitExceeded(fmt.Sprintf("die term exceeded maximum roll count of %d", ctx.limits.MaxRollsPerDie))
	}

	ctx.totalRolls++
	if ctx.totalRolls > ctx.limits.MaxRollsTotal {
		return ErrLimitExceeded(fmt.Sprintf("roll exceeded maximum total roll count of %d", ctx.limits.MaxRollsTotal))
	}
	return nil
}

// Result is a collection of die rolls and a count of successes.
type Result struct {
	Results   []DieRoll
	Total     int
	Successes int
}

// Len is the number of results.
func (r *Result) Len() int {
	return len(r.Results)
}

// Less return true if DieRoll at index i is less than the one at index j.
func (r *Result) Less(i, j int) bool {
	return r.Results[i].Result < r.Results[j].Result
}

// Swap swaps the DieRoll at index i with the one at index j.
func (r *Result) Swap(i, j int) {
	r.Results[i], r.Results[j] = r.Results[j], r.Results[i]
}

type vmValue struct {
	Result   Result
	Modifier int
	Num      float64
	IsNum    bool
}

// numeric returns the value used by arithmetic operations. Roll results fall
// back to their integer total.
func (v vmValue) numeric() float64 {
	if v.IsNum {
		return v.Num
	}
	return float64(v.Result.Total)
}

// EvaluateProgram executes a compiled roll program using DefaultLimits.
func EvaluateProgram(program *Program) (Result, error) {
	return EvaluateProgramWithLimits(program, DefaultLimits)
}

// EvaluateProgramWithLimits executes a compiled roll program using explicit safety limits.
func EvaluateProgramWithLimits(program *Program, limits Limits) (Result, error) {
	if program == nil {
		return Result{}, nil
	}

	ctx := &rollContext{limits: limits.normalized()}
	value, err := runProgram(ctx, program)
	if err != nil {
		return Result{}, err
	}
	return value.Result, nil
}

// runProgram runs a compiled program against a shared roll context so that
// nested side expressions observe the same limits.
func runProgram(ctx *rollContext, program *Program) (vmValue, error) {
	if program.MaxDepth > ctx.limits.MaxEvalDepth {
		return vmValue{}, ErrLimitExceeded(fmt.Sprintf("roll exceeded maximum evaluation depth of %d", ctx.limits.MaxEvalDepth))
	}

	stack := make([]vmValue, 0, len(program.Code))

	for _, instruction := range program.Code {
		switch instruction.Op {
		case OpRollDice:
			if instruction.Arg < 0 || instruction.Arg >= len(program.DiceTerms) {
				return vmValue{}, fmt.Errorf("invalid dice term index %d", instruction.Arg)
			}
			term := program.DiceTerms[instruction.Arg]
			result, err := evalDiceTerm(ctx, term)
			if err != nil {
				return vmValue{}, err
			}
			stack = append(stack, vmValue{Result: result, Modifier: term.Modifier})
		case OpRollGroup:
			if instruction.Arg < 0 || instruction.Arg >= len(program.GroupTerms) {
				return vmValue{}, fmt.Errorf("invalid group term index %d", instruction.Arg)
			}
			term := program.GroupTerms[instruction.Arg]
			if term.ChildCount > len(stack) {
				return vmValue{}, fmt.Errorf("group term %d requires %d child values, stack has %d", instruction.Arg, term.ChildCount, len(stack))
			}
			children := append([]vmValue(nil), stack[len(stack)-term.ChildCount:]...)
			stack = stack[:len(stack)-term.ChildCount]
			result := evalGroupTerm(term, children)
			stack = append(stack, vmValue{Result: result, Modifier: term.Modifier})
		case OpPushNumber:
			stack = append(stack, vmValue{Result: Result{Total: instruction.Arg}, Num: float64(instruction.Arg), IsNum: true})
		case OpBinary:
			if len(stack) < 2 {
				return vmValue{}, fmt.Errorf("binary operator %d requires two values on the stack", instruction.Arg)
			}
			b := stack[len(stack)-1]
			a := stack[len(stack)-2]
			stack = stack[:len(stack)-2]

			value, err := applyBinary(BinaryOpType(instruction.Arg), a.numeric(), b.numeric())
			if err != nil {
				return vmValue{}, err
			}

			stack = append(stack, vmValue{
				Result: Result{
					Total:     int(value),
					Results:   append(append([]DieRoll{}, a.Result.Results...), b.Result.Results...),
					Successes: a.Result.Successes + b.Result.Successes,
				},
				Num:   value,
				IsNum: true,
			})
		case OpFunc:
			if len(stack) < 1 {
				return vmValue{}, fmt.Errorf("function %d requires a value on the stack", instruction.Arg)
			}
			a := stack[len(stack)-1]
			stack = stack[:len(stack)-1]

			value, err := applyFunc(FuncType(instruction.Arg), a.numeric())
			if err != nil {
				return vmValue{}, err
			}

			stack = append(stack, vmValue{
				Result: Result{
					Total:     int(value),
					Results:   a.Result.Results,
					Successes: a.Result.Successes,
				},
				Num:   value,
				IsNum: true,
			})
		default:
			return vmValue{}, fmt.Errorf("unsupported opcode %d", instruction.Op)
		}
	}

	if len(stack) != 1 {
		return vmValue{}, fmt.Errorf("program left %d results on the VM stack", len(stack))
	}

	return stack[0], nil
}

// applyBinary performs an arithmetic operation, returning an error for unsafe divisors.
func applyBinary(op BinaryOpType, a, b float64) (float64, error) {
	switch op {
	case BinaryAdd:
		return a + b, nil
	case BinarySub:
		return a - b, nil
	case BinaryMul:
		return a * b, nil
	case BinaryDiv:
		if b == 0 {
			return 0, ErrDivisionByZero("division by zero")
		}
		return a / b, nil
	case BinaryMod:
		if b == 0 {
			return 0, ErrDivisionByZero("modulus by zero")
		}
		return math.Mod(a, b), nil
	case BinaryPow:
		return math.Pow(a, b), nil
	default:
		return 0, fmt.Errorf("unsupported binary operator %d", op)
	}
}

// applyFunc performs a math function on a single value.
func applyFunc(fn FuncType, x float64) (float64, error) {
	switch fn {
	case FuncFloor:
		return math.Floor(x), nil
	case FuncRound:
		return math.Floor(x + 0.5), nil
	case FuncCeil:
		return math.Ceil(x), nil
	case FuncAbs:
		return math.Abs(x), nil
	default:
		return 0, fmt.Errorf("unsupported function %d", fn)
	}
}

// resolveDie returns the concrete die for a term, evaluating a dynamic side
// expression at roll time when present.
func resolveDie(ctx *rollContext, term DiceTerm) (Die, error) {
	if term.Sides == nil {
		return term.Die, nil
	}

	value, err := runProgram(ctx, term.Sides)
	if err != nil {
		return nil, err
	}

	sides := value.numeric()
	if sides != math.Trunc(sides) {
		return nil, ErrInvalidDieSize(fmt.Sprintf("die size %v is not a whole number", sides))
	}
	return NormalDie(int(sides)), nil
}

func evalDiceTerm(ctx *rollContext, term DiceTerm) (result Result, err error) {
	die, err := resolveDie(ctx, term)
	if err != nil {
		return Result{}, err
	}

	if err = validateDieLimits(die, ctx.limits); err != nil {
		return
	}

	if term.Multiplier == 0 {
		return
	}

	totalMultiplier := 1
	if term.Multiplier < 0 {
		totalMultiplier = -1
	}

	rollCount := term.Multiplier * totalMultiplier
	if rollCount > ctx.limits.MaxRollsPerDie {
		return Result{}, ErrLimitExceeded(fmt.Sprintf("die term exceeded maximum roll count of %d", ctx.limits.MaxRollsPerDie))
	}

	dieRolls := 0
	for i := 0; i < rollCount; i++ {
		if err = ctx.recordRoll(&dieRolls); err != nil {
			return Result{}, err
		}
		result.Results = append(result.Results, die.Roll())
	}

	for i, roll := range result.Results {
	RerollOnce:
		for _, reroll := range term.Rerolls {
			for reroll.Match(roll.Result) {
				if err = ctx.recordRoll(&dieRolls); err != nil {
					return Result{}, err
				}
				roll = die.Roll()
				result.Results[i] = roll
				if reroll.Once {
					break RerollOnce
				}
			}
		}
	}

	if term.Exploding != nil {
		switch term.Exploding.Type {
		case Exploding:
			for _, roll := range result.Results {
				for term.Exploding.Match(roll.Result, die) {
					if err = ctx.recordRoll(&dieRolls); err != nil {
						return Result{}, err
					}
					roll = die.Roll()
					result.Results = append(result.Results, roll)
				}
			}
		case Compounded:
			compound := 0
			for _, roll := range result.Results {
				for term.Exploding.Match(roll.Result, die) {
					compound += roll.Result
					if err = ctx.recordRoll(&dieRolls); err != nil {
						return Result{}, err
					}
					roll = die.Roll()
				}
			}
			result.Results = append(result.Results, DieRoll{Result: compound, Symbol: strconv.Itoa(compound)})
		case Penetrating:
			for _, roll := range result.Results {
				for term.Exploding.Match(roll.Result, die) {
					if err = ctx.recordRoll(&dieRolls); err != nil {
						return Result{}, err
					}
					roll = die.Roll()
					newRoll := roll
					newRoll.Result--
					newRoll.Symbol = strconv.Itoa(newRoll.Result)
					result.Results = append(result.Results, newRoll)
				}
			}
		}
	}

	applyLimit(term.Limit, &result)
	applySuccess(term.Success, term.Modifier, &result)
	applyFailure(term.Failure, term.Modifier, &result)
	applySort(term.Sort, &result)
	finaliseTotals(term.Success, term.Failure, term.Modifier, totalMultiplier, &result)
	applyMatch(term.Match, &result)

	return result, nil
}

func evalGroupTerm(term GroupTerm, children []vmValue) (result Result) {
	for _, child := range children {
		if term.Combined {
			for _, res := range child.Result.Results {
				result.Results = append(result.Results, DieRoll{
					Result: res.Result + child.Modifier,
					Symbol: strconv.Itoa(res.Result + child.Modifier),
				})
			}
		} else {
			result.Results = append(result.Results, DieRoll{Result: child.Result.Total, Symbol: strconv.Itoa(child.Result.Total)})
		}
	}

	applyLimit(term.Limit, &result)
	applySuccess(term.Success, term.Modifier, &result)
	applyFailure(term.Failure, term.Modifier, &result)
	finaliseTotals(term.Success, term.Failure, term.Modifier, 1, &result)

	if term.Negative {
		result.Total *= -1
		for i, roll := range result.Results {
			roll.Result *= -1
			if roll.Symbol != "" {
				roll.Symbol = strconv.Itoa(roll.Result)
			}
			result.Results[i] = roll
		}
	}

	return result
}

func validateDieLimits(die Die, limits Limits) error {
	limits = limits.normalized()

	var size int
	switch d := die.(type) {
	case NormalDie:
		size = int(d)
	case PercentileDie:
		size = 100
	case FateDie:
		size = 3
	default:
		return fmt.Errorf("unsupported die type %T for limit validation", die)
	}

	if size < 2 {
		return ErrUnsafeDie(die.String())
	}
	if size > limits.MaxDieSize {
		return ErrLimitExceeded(fmt.Sprintf("die size %d exceeds maximum %d", size, limits.MaxDieSize))
	}
	return nil
}

func applyLimit(limitOp *LimitOp, result *Result) {
	if limitOp != nil {
		var rolls Result
		rolls.Results = result.Results[:]
		sort.Sort(&rolls)

		limit := min(limitOp.Amount, len(rolls.Results))

		switch limitOp.Type {
		case KeepHighest:
			rolls.Results = rolls.Results[len(rolls.Results)-limit:]
		case KeepLowest:
			rolls.Results = rolls.Results[:limit]
		case DropHighest:
			rolls.Results = rolls.Results[:len(rolls.Results)-limit]
		case DropLowest:
			rolls.Results = rolls.Results[limit:]
		}

		m := make(map[int]int, len(rolls.Results))
		for _, r := range rolls.Results {
			m[r.Result]++
		}

		newResults := make([]DieRoll, 0, len(rolls.Results))
		for _, a := range result.Results {
			if b, ok := m[a.Result]; ok {
				newResults = append([]DieRoll{a}, newResults...)
				b--
				if b == 0 {
					delete(m, a.Result)
				}
			}
		}

		result.Results = newResults
	}
}

// applyMatch counts the distinct face values that match often enough, and for a
// counting (mt) modifier replaces the total with that count.
func applyMatch(matchOp *MatchOp, result *Result) {
	if matchOp == nil {
		return
	}

	counts := make(map[int]int, len(result.Results))
	for _, roll := range result.Results {
		counts[roll.Result]++
	}

	matches := 0
	for value, count := range counts {
		if count < matchOp.MinCount {
			continue
		}
		if matchOp.Comparison != nil && !matchOp.Comparison.Match(value) {
			continue
		}
		matches++
	}

	if !matchOp.Visual {
		result.Total = matches
	}
}

func applySuccess(successOp *ComparisonOp, modifier int, result *Result) {
	if successOp != nil {
		for _, roll := range result.Results {
			if successOp.Match(roll.Result + modifier) {
				result.Successes++
			}
		}
	}
}

func applyFailure(failureOp *ComparisonOp, modifier int, result *Result) {
	if failureOp != nil {
		for _, roll := range result.Results {
			if failureOp.Match(roll.Result + modifier) {
				result.Successes--
			}
		}
	}
}

func applySort(sortType SortType, result *Result) {
	switch sortType {
	case Unsorted:
		return
	case Ascending:
		sort.Sort(result)
	case Descending:
		sort.Sort(sort.Reverse(result))
	}
}

func finaliseTotals(successOp, failureOp *ComparisonOp, modifier, multiplier int, result *Result) {
	if successOp == nil && failureOp == nil {
		for _, roll := range result.Results {
			result.Total += roll.Result
		}
		result.Total += modifier
		result.Total *= multiplier
	} else {
		result.Total = result.Successes
	}
}
